version: "3.0"

services:
  monolith:
    image: goldenfoil/platform.monolith:latest
    ports:
      - "0.0.0.0:3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: goldenfoil-test
        awslogs-region: eu-west-1
        awslogs-stream-prefix: monolith

  webapp-server:
    image: goldenfoil/platform.webapp-server:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: goldenfoil-test
        awslogs-region: eu-west-1
        awslogs-stream-prefix: webapp
